### PR TITLE
ZPL and license update

### PR DESCRIPTION
**Pull request by Crosse**
ZenPackLib >= 2.0 no longer requires that a ZenPack ship `zenpacklib.py`, from what @daviswr tells me. Removing that should allow me to license the rest of the code with a usefully-permissive license (MIT, in this case). In addition to that, I also ran the Python code through [black](https://black.readthedocs.io/en/stable/), because ain't nobody got time for code style issues. Might as well get that over with now.

Before merging this, since I've been out of the Zenoss- and ZenPack games for so long, I'd love to get input from @daviswr and @baileytj3 to make sure it's correct. Because of running `black`, it's probably best to look at the individual commits.

### CODE REVIEW

**Comment by Crosse** [comment]
…specifically just the first commit, 34c6151, as that's the only one that addresses the ZPL stuff. The other two are just noise.

**Review by baileytj3 — APPROVED** [review]
Looks good to me. Whats your formatter have against single quotes?

**Comment by Crosse** [comment]
I have literally no idea, but the great thing is I never have to ask. 😆

**Comment by Crosse** [comment]
…but you made me go look!

> The main reason to standardize on a single form of quotes is aesthetics. Having one kind of quotes everywhere reduces reader distraction. […] Why settle on double quotes? They anticipate apostrophes in English text. They match the docstring standard described in PEP 257. An empty string in double quotes ("") is impossible to confuse with a one double-quote regardless of fonts and syntax highlighting used. On top of this, double quotes for strings are consistent with C which Python interacts a lot with.

(from https://black.readthedocs.io/en/stable/the_black_code_style.html)

**Comment by baileytj3** [comment]
You just had to go all official and RTFM on me.

**Comment by Crosse** [comment]
It's half my job at $WORK, so it's not that far of a reach...

**Pull request merged**
